language: ruby
rvm:
- 2.7.0
node_js:
- lts/*
bundler_args: --jobs=2
script:
  - bundle exec rails db:setup
  - bundle exec rails webpacker:compile
  - bundle exec rspec
cache: bundler
services:
  - postgresql